adjective1 = input("Enter an adjective ")
name1 = input("Enter a name: ")
number = input("Enter a number: ")
name2 = input("Enter another name: ")
town1 = input("Enter a town name ")
town2 = input("Enter a different town name ")
adjective2 = input("Enter an adjective: ")

print()
print("A new and "+ adjective1 + " movie is coming soon!")
print("It's about "+name1 +" and the  "+ number + " python Programmers. ")
print(name1+" is a computing wizard whose talent thretens "+name2+". ")
print(name1 + " is forced to flee from "+town1+" and hides in nearby "+town2+".")
print("BUt "+name2 + " finds "+name1+" and casts a "+adjective2+" spell.")
